database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "anhiuemlove33"
  db_name: "bmt_product"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
redis:
  host: "redis"
  port: 6379
  password: ""
  database: 0
kafka:
  kafka_broker_1: "kafka-1:9092"
  kafka_broker_2: "kafka-2:9093"
  kafka_broker_3: "kafka-3:9094"