// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flims.query.sql

package sqlc

import (
	"context"
)

const getFilmByTitle = `-- name: GetFilmByTitle :one
SELECT id, title, description, release_date, duration
FROM films
WHERE title = $1
`

func (q *Queries) GetFilmByTitle(ctx context.Context, title string) (Films, error) {
	row := q.db.QueryRow(ctx, getFilmByTitle, title)
	var i Films
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ReleaseDate,
		&i.Duration,
	)
	return i, err
}
