// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetFilmByTitle(ctx context.Context, title string) (Films, error)
}

var _ Querier = (*Queries)(nil)
