// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"bmt_product_service/db/sqlc"
	"bmt_product_service/internal/controllers"
	"bmt_product_service/internal/implementations"
	"bmt_product_service/internal/injectors/provider"
)

// Injectors from product.controller.wire.go:

func InitProductController() (*controllers.ProductController, error) {
	pool := provider.ProvidePgxPool()
	sqlStore := sqlc.NewStore(pool)
	iProduct := implementations.NewProductService(sqlStore)
	productController := controllers.NewProductController(iProduct)
	return productController, nil
}
