// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"bmt_product_service/db/sqlc"
	"bmt_product_service/internal/controllers"
	"bmt_product_service/internal/implementations/message_broker/consummers"
	"bmt_product_service/internal/implementations/message_broker/writer"
	"bmt_product_service/internal/implementations/product"
	"bmt_product_service/internal/implementations/redis"
	"bmt_product_service/internal/injectors/provider"
)

// Injectors from film_upload_consummer.wire.go:

func InitFilmUploadConsummer() (*consummers.FilmUploadConsummer, error) {
	queries := provider.ProvideQueries()
	filmUploadConsummer := consummers.NewFilmUploadConsummer(queries)
	return filmUploadConsummer, nil
}

// Injectors from product.controller.wire.go:

func InitProductController() (*controllers.ProductController, error) {
	pool := provider.ProvidePgxPool()
	iMessageBroker := writer.NewKafkaWriter()
	iStore := sqlc.NewStore(pool, iMessageBroker)
	iRedis := redis.NewRedisClient()
	iFilm := product.NewProductService(iStore, iRedis)
	productController := controllers.NewProductController(iFilm)
	return productController, nil
}
